### PR TITLE
Major user configuration refactor

### PR DESCRIPTION
**Pull request by Draeggiar**
In this PR I made some solid changes to ... basicaly everything related to working with user configuration. I will try to briefly explain here every major thing that I did and why I did it, but if something is unclear or require additional clarification, just let me know.

### 1. Changed structure of UserConfig
Current, flat structure of configuration file felt a little ... unnatural. Informations was scattered and duplicated between few collections, witch was hard to use and understand. Storing addons in a list is much more intuitive and easier to use, for example in LINQ queries. 

### 2. Changed format of config file from yaml to xml
It was a natural consequence of new config format. I have nothing aganist YAML, but storing complex collection in it is a bad idea - it becomes much less readable. XML on the other hand is perfect for such matter, and gives much freedom as it comes to serialize our list. I wrote a method that will migrate old config into new, so no data should be lost. 

### 3. Moved application version from config file to assembly version. 
This one is arguable, I just find it cleaner to have assembly in the acctual app version.

### 4. Made most classes non-static
Overusing static classes is considered a bad practice. Maybe it speeds up the development process at first, but at the end of the day you end up in big static mess, when everything is related to everything. Also it prevents garbage collector from doing its job. Alsox2 in this case it was practicaly imposible to write unit tests, because there was no way to mock anything. 

### 5. Removed option to set defaultly selected addons. Installed addons will now be selected instead.
This is the default behavior of other mod managers (i.e. Nexus, Skyrim launcher), and it felt unnatural that installed addons were not checked by default. This should be done as another feature in another PR, but it was just easier to not implement it when I was rewriting configuration. Maybe in future each addon should have its own separate status button instead of checkbox ?

---

Any coments and sugestions appreciated. As these are some major changes you may want to tinker with it a bit, to make sure everything works as before.
I would also like to write some unit tests, as it is now possible, but im not sure how much free time I will have to do so.

### CODE REVIEW

**Comment by fmmmlee** [comment]
Woke up and saw this, I have an assignment to complete this weekend but after that I'll give this the attention it deserves. Looks like a lot of substantial and justified changes --- I agree that the current implementation has plenty of room for improvement.

Also strongly agree about the unit testing. I banged out the original application in a few weeks and released it, and when some months later I thought it'd be a good idea to put in basic tests to avoid breaking things in a release I realized how difficult mocking up everything properly would be and promptly abandoned the idea. Hopefully your changes will alleviate this somewhat.

**Comment by Draeggiar** [comment]
Great to hear, I was a little afraid to put up such big changes out of the blue :) I love your project though and I would like to help with development in my free time.

**Comment by fmmmlee** [comment]
Sorry for taking so long --- do you have a build of this version that I could test out? All your changes make sense and I'm fine with as long as the experience for the end user moving over is smooth and the configuration gets transferred to the new format with no hiccups.

**Comment by Draeggiar** [comment]
Sorry for late response, I've been somewhat busy myself. 
Sure, here is the build of my fork, which includes this changes:
[UOAOM_Draeggiar-v1.2.2.1.zip](https://github.com/fmmmlee/GW2-Addon-Manager/files/5453253/UOAOM_Draeggiar-v1.2.2.1.zip)
I've tested few scenarios and configuration seemed to migrate fine, but maybe you will find something.

**Review by fmmmlee — APPROVED** [review]
Finally dove into the changes made here and have some feedback (all of it good!)

Points from PR:
**1 - Config file structure**: Definitely agree. Looking at it before, it didn't seem to need much changing, but seeing the structure you chose, I concur that it makes more sense to keep all data associated with an addon within a single entry rather than spread out over multiple loose collections.

**2 - Format of config file**. I'm with you on this one, too. While the old UserConfig fit just fine in yaml, the newer, more intuitive structure you chose for UserConfig would not have translated well to yaml, so the shift to xml makes sense.

**3 - Version location**. Using assembly version instead of keeping it in the config file is a better choice, I agree --- this was my first C# program, so I went with what I knew at the time for versioning.

**4 - Limiting use of static classes**. Yeah, I certainly wasn't following good design practices when I threw together the first beta and that set the tone for future additions, heh. Thanks for making this change, I'm sure it took a while.

**5 - Default addon selection**. Agreed, the changes make it more intuitive.

All in all, thanks for the work you put in on this and I'll merge these changes now. I'll have a peek at the current issues and see if there's anything that I can fix quickly, and after that I'll publish a new release. Thanks again!

**Pull request merged**
