### PR TITLE
Fixed addons options

### LINKED ISSUE #88: can't remove separated addon.
### Please attach a copy of config.yaml or config.ini to the issue.
[config.zip](https://github.com/fmmmlee/GW2-Addon-Manager/files/5759874/config.zip)

**Describe the bug**
need to reinstal d912pxy, nothing happens when i chose delete.
only way it remove all addons, so i lose other useful settings.

**To Reproduce**

**Additional context**

**don't forget to attach the config file to the issue**

### LINKED ISSUE #95: Unable to disable addons
I normally run with D912proxy on but as I'm re-doing the story with a friend I want to turn it off to avoid the crashes during some of the cinematics. 

When I go into the Addon manager, select D912 proxy and hit disable, it prompts me for confirmation which I provide. But the add on does not show as "disabled." 

Launching the game client confirms D912 proxy is still running. The only way I've been able to get around this is to reset to a clean install and just install the other add ons while leaving out D912x.

I had this problem on 1.2.2 as well but somehow I was able to get it to work though I don't remember what I did.

### PR DESCRIPTION
**Pull request by Draeggiar**
Addon name in config was different than in view model, so getting addon by name didn't work. 

Fixes #95
Fixes #88

### CODE REVIEW

**Comment by methos237** [comment]
Can we get a new build with this pull request merged?

**Comment by Draeggiar** [comment]
I made a pre-release on my fork, you can check it out [here](https://github.com/Draeggiar/GW2-Addon-Manager/releases/tag/1.3.1). It contains fixes from currently opened pull requests, hope this will do until official version is released.

**Review by methos237 — APPROVED** [review]

**Comment by sho-87** [comment]
+1 for a merge. I'm having the same problems with trying to uninstall addons

**Comment by bluenote73** [comment]
> I made a pre-release on my fork, you can check it out [here](https://github.com/Draeggiar/GW2-Addon-Manager/releases/tag/1.3.1). It contains fixes from currently opened pull requests, hope this will do until official version is released.

Thank you for this, I've been using your release for a while now and it's a real life saver. 
It seems enabling/disabling addons also is bugged, I wonder if you could fix that too?

**Comment by bluenote73** [comment]
@Draeggiar Thanks, I reported the various disable/enable/duplicate issues here: https://github.com/fmmmlee/GW2-Addon-Manager/issues/116

**Pull request closed without merging**
